### PR TITLE
Don't attempt to join rooms with type group

### PR DESCRIPTION
**Pull request by twouters**
Not sure what this change breaks but it fixes Sorunome/mx-puppet-slack#59 for me.

### CODE REVIEW

**Comment by Sorunome** [comment]
Shouldn't it be "mpim" and not "group"?

**Comment by twouters** [comment]
That's what I tried too, but that didn't work :)

**Comment by twouters** [comment]
maybe both are needed? I'll check if mpim conversations work properly. 

https://api.slack.com/types/group

**Comment by twouters** [comment]
Ok, both room types need this but the bridge doesn't join new rooms now obviously :D

**Comment by Sorunome** [comment]
Would you mind adding both to the PR, then?

**Comment by Sorunome** [comment]
thanks, sorry it took so long

**Pull request merged**
