### PR TITLE
add support for sendCommand packet

### PR DESCRIPTION
**Pull request by matejdro**
PR adds support for undocumented command that allows users to send slash commands to the channel: https://github.com/ErikKalkoken/slackApiDoc/blob/master/chat.command.md

### CODE REVIEW

**Comment by Sorunome** [comment]
Does this also work with bot tokens? ("xoxc") If not, maybe don't send for those, just to be sure? (`this.isBotToken()`)

**Comment by matejdro** [comment]
To be honest, I have no idea. I also have no bot tokens on hand to test it (I'm only using legacy tokens at the moment).

**Comment by Sorunome** [comment]
Do you have a simple code snippet so that soru can test if it works with a bot token? Also, would she need to test in a slack team with some bot stuffs for custom commands configured?

**Comment by matejdro** [comment]
You can just use `channel.sendCommand("/me", "hello world")`, which triggers `/me hello world` command. That command is present on every slack team, no custom commands needed.

**Comment by Sorunome** [comment]
Finally got to this & indeed, `xoxb` tokens to not work - both `xoxp` and `xoxc` seem to work, though

**Comment by matejdro** [comment]
Wow `xoxp` tokens working is nice surprise. That means that we can still use this feature after legacy tokens die.

**Comment by Sorunome** [comment]
only tested with an xoxp legacy token.... :S

Am 3. April 2020 05:43:58 MESZ schrieb "Matej Drobnič" <notifications@github.com>:

**Pull request merged**
